name: 'Auto Assign'
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          configuration-path: '.github/some_name_for_configs.yml' # Only needed if you use something other than .github/auto_assign.yml
          
          # Set to true to add reviewers to pull requests
  addReviewers: true

# Set to true to add assignees to pull requests
  addAssignees: false

# A list of reviewers to be added to pull requests (GitHub user name)
  reviewers:
    - zerbb
    - zacharyrobin

# A number of reviewers added to the pull request
# Set 0 to add all the reviewers (default: 0)
  numberOfReviewers: 0
