name: Sync Fork

on:
  schedule:
    - cron: '*/5 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.3
        with:
          owner: zacharyrobin
          github_token: ${{ secrets.GH_API }} 
          base: main
          head: main
          auto_approve: flase
          ignore_fail: true
          pr_title: Fork Auto Sync
          pr_message: Upstream repository has been changed - Please review changes 
