name: Sync Fork

on:
  schedule:
    - cron: '*/5 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          token: ${{ secrets.GH_API }}
          owner: zacharyrobin
          base: main
          head: main
          pr_title: Fork Auto Sync
          pr_message: Upstream repository has been changed - Please review changes 
